### ISSUE TITLE
Add Support for "Policy Extensions"

### ISSUE THREAD

**Issue by rany2** [flathub/com.brave.Browser#103]
Something like https://github.com/flathub/org.chromium.Chromium/tree/master/examples/policies/google-safe-search

**Comment by cthu1hoo** [comment]
I've looked over this and I'm not sure - can this be done without recompiling and patching Brave to use a different directory for policies under '/app/'? Adding extension points (or, really, anything) to '/etc/' doesn't seem to work.

**Comment by refi64** [comment]
It can't be, it's hardcoded into Chromium right now. I've been considering trying to add an env variable to control this and seeing what upstream thinks, since it's an issue we're having in Chrome land too (for native messaging hosts, especially, though the semantics around that are going to be...awkward).

What you *can* do right now is add `--filesystem=host-etc` and then [manually pull in the host's policies into the Flatpak](https://github.com/flathub/com.google.Chrome/blob/beta/chrome.sh).

**Comment by cthu1hoo** [comment]
Thanks, this looks like a serviceable workaround. I've tried doing ``flatpak enter com.brave.Browser`` and placing stuff into ``/etc/brave/policy/managed`` manually but it didn't work. Maybe I misunderstood things and this creates a separate sandbox.

**Comment by rany2** [comment]
It's /etc/brave/*policies* not policy, hopefully just a small typo ;)
