### ISSUE TITLE
Can any one explain how to get ads on brave in VMs

### ISSUE THREAD

**Issue by anshulbawri** [flathub/com.brave.Browser#104]
I have tried multiple times to install brave on windows 7 on a VM, But I don't receive ads.

**Comment by rany2** [comment]
I don't understand how this is related to the Flatpak? I don't think you could install Flatpak on Windows 7.

**Comment by anshulbawri** [comment]
So could you explain to me how I could use flatpak and Install brave?

**Comment by TheEvilSkeleton** [comment]
You need to have Linux installed on your system. Since you mentioned that you have Windows 7 installed, your operating system is incompatible, and therefore this subject is out of scope of our support.

You can download and install Brave for Windows here: https://brave.com/download/.

If you want to use a Linux distribution, then you will need to install a distribution listed here: https://flatpak.org/setup/, and then follow the instructions for the distribution.

I'm going to lock this issue because, as said previously, this is out of scope. If you need help, then you can ask help in a Linux support forums or Windows.
