### ISSUE TITLE
Request to officially support the Brave Flatpak

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.brave.Browser#137]
Hey @mihaiplesa, I noticed that you occasionally approve some of the PRs made by the bot. I also noticed that you are employee at Brave. Would like to maintain this repo with us? Perhaps even officially?

**Comment by mihaiplesa** [comment]
Hey @TheEvilSkeleton, that is true. How can we help?

**Comment by rany2** [comment]
You could help by having Brave officially maintain the flatpak.

This means that you could:
- build it from source and incorporate flatpak specific patches from the Chromium flatpak (drop Zypak reliance)
- make it an official package instead of having it be a community-maintained one
- increase your control and say in how this flatpak functions instead of relying on third-parties 

Also Flathub generally prefers if the official developers maintain their Flatpak as well, but it's not a requirement.

**Comment by TheEvilSkeleton** [comment]
I also want to add that you, as a maintainer, package once and deploy it everywhere. Users can run the same Brave Flatpak on Fedora, Pop!_OS, Arch, etc. On the other hand, `.deb`, `.rpm` and other formats are only available on specific distributions.

**Comment by mihaiplesa** [comment]
Hello again and thanks for the contributions so far. For example we've brought Snaps in-house (https://brave.com/linux/#snap) and many things could have gone better.

We'd have to scale a bit in order to offer quality support for Flatpaks and this will take some time. Hope that helps.

**Comment by TheEvilSkeleton** [comment]
Sure.

**Comment by xrishox** [comment]
please consider supporting this flatpak officially. snap is the black sheep of universal packaging hated by nearly everyone. the entire industry aside from canonical is backing flatpak up to and including valve on the steam deck. on top of that people that are running immutable operating systems like fedora silverblue, valve's steamos, or endless os can't run snaps even if they wanted to because snap requires modifying the root filesystem.

**Comment by AndrejSh3** [comment]
The only reason I started to use brave was because of the flatpak version, as I am on silverblue, and it would be great if it were officially supported!

**Comment by illtellyoulater** [comment]
> We'd have to scale a bit in order to offer quality support for Flatpaks and this will take some time. Hope that helps.

Hi @mihaiplesa, do you have any updates on official Flatpak support by Brave? It's been ~2 years after your comment and so far the trend in favor of Flatpak has been clearly confirmed.

> For example we've brought Snaps in-house (https://brave.com/linux/#snap) and many things could have gone better.

Seeing how that page in 2024 stills says that the Snap version of Brave is [not yet working as well as your other official packages](https://brave.com/linux/#snap), perhaps this could be the perfect time to switch over to Flatpak? With the level of adoption it achieved so far, it's hard to imagine that transitioning to it wouldn't significantly streamline Brave's workload and support processes.

**Comment by mihaiplesa** [comment]
@rany2 this can be reopened. We'd like to know what steps you see as next for the transfer.

**Comment by rany2** [comment]
@mihaiplesa I'm already on the Slack chat, so we can discuss this further there.

**Comment by Raul1198** [comment]
is Brave Officially on Flathub ?
 just open the [Brave Flathub page](https://flathub.org/apps/com.brave.Browser) there it is having a Verified Badge and  no note in description stating ''This wrapper is not verified by, affiliated with, or supported by Brave." or something similar

**Comment by rany2** [comment]
Yes, it's sort of official now but I'm still maintaining it for the time being. I'm working with the Brave team so they could start to take it from here.

**Comment by rany2** [comment]
I think this could actually be closed now though
