### ISSUE TITLE
No rewards ads

### ISSUE THREAD

**Issue by TheCultLeader666** [flathub/com.brave.Browser#95]
It does not seem like rewards notification ads are functional. I have looked through the logs in brave://rewards-internals and the only thing of note is this:
```
[Dec 11, 2021, 11:29:04.2 AM:ERROR:publisher.cc(774)] Publisher info not found
```
I have also manually enabled custom ad notifications in brave://flags, because I know that the old native ones were broken in Wayland, but that does not seem to have helped.

**Comment by rany2** [comment]
Does it work on the official debian/redhat builds?

**Comment by TheCultLeader666** [comment]
> Does it work on the official debian/redhat builds?

No idea, I'm on silverblue. I could possibly try in a VM though.

**Comment by TheCultLeader666** [comment]
I will (attempt) to install the native package on microos, play around for a bit, and see if it works.

**Comment by refi64** [comment]
You can install native RPMs onto Silverblue, I did that with Chrome for a while before the Flatpak was created.

**Comment by TheCultLeader666** [comment]
Not brave. https://github.com/brave/brave-browser/issues/7710

**Comment by TheEvilSkeleton** [comment]
@TheCultLeader666 try to use Toolbx. You can use `dnf` inside the container and install Brave the Fedora Workstation way.

**Comment by TheCultLeader666** [comment]
Ok, I have successfully gotten ads on Pantheon, but I'm pretty sure Pantheon is x11. I don't know if that helps. I could also try using the flatpak on Pantheon, although I don't know of an easy way to get flathub beta flatpakref files.

**Comment by TheEvilSkeleton** [comment]
You can add the flathub-beta remote and install Brave afterwards, https://github.com/flathub/flathub#using-the-flathub-repository.

**Comment by anshulbawri** [comment]
Hey buddy could You explain how you got ads on brave on a VM?

**Comment by anshulbawri** [comment]
> Ok, I have successfully gotten ads on Pantheon, but I'm pretty sure Pantheon is x11. I don't know if that helps. I could also try using the flatpak on Pantheon, although I don't know of an easy way to get flathub beta flatpakref files.

Could you explain to me how you got ads on Pantheon.

**Comment by mpi3d** [comment]
Ad notifications doesn't work on XWayland. But they work on native Wayland. So first you need to add `--enable-features=UseOzonePlatform --ozone-platform=wayland` in your Brave flags.

But with Flatpak this isn't enough since Flatpak disallow communication on D-Bus. So you need to allow Brave to talk to `org.gnome.Mutter.IdleMonitor.*` on the D-Bus Session.
@rany2 @TheEvilSkeleton @refi64 Maybe this D-Bus Session talk can be implemented by default in this Flatpak?

Also, enabling custom ad notifications is not necessary.

**Comment by refi64** [comment]
You've tested that it fixes the issue? If so, I'd imagine the other maintainers would be rather happy with a PR to add that?

**Comment by mpi3d** [comment]
Yes it works:

![Screenshot from 2022-02-25 18-00-13](https://user-images.githubusercontent.com/26822551/155758761-9fb1533c-d398-471a-94a3-3ef3c5153ee0.png)

![Screenshot from 2022-02-25 18-01-20](https://user-images.githubusercontent.com/26822551/155758763-62098fe2-c56a-43ea-ade3-e187ba9bdecc.png)

I'm just not sure if it will work on other desktop environement because Mutter is specific to GNOME.

Also I will not include `--enable-features=UseOzonePlatform --ozone-platform=wayland` flags in the PR because this is not Flatpak specific (It's also required on native install to get ads)
